# Generated by Django 2.1.3 on 2018-11-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_field',
            field=models.ImageField(upload_to=''),
        ),
    ]
